### ISSUE TITLE
Web Page Comes Up But Render Not Displayed

### ISSUE THREAD

**Issue by jmwright** [zignig/cqparts-server#1]
Ubuntu 17.10 64-bit

I run the server this way with no errors on the command line.
```
./server test.py
```
The page pulls up without errors but the contents of my file doesn't render. I'm using the cqparts `display` method, should I be using something else? I've also got the environment variable set.

**Comment by jmwright** [comment]
I forgot to check the JavaScript console. Let me do that before you spend any time on this issue.

**Comment by zignig** [comment]
It actually watches a directory for any changes to .py files, so ./server -d <working directory> , also if you run a script with display(object) in it the server will display it.

Still very much pre-alpha , but keep the issues coming if you are using it.

**Comment by jmwright** [comment]
Ah, ok. I didn't realize it had to be run against a directory.

> Still very much pre-alpha

Understood. Thanks for putting this out there. Multiple CadQuery community members have hacked together their own variations enabling this type of workflow. I was curious how it works. 

> but keep the issues coming if you are using it.

This is the first time I've ever touched Go, so filing issues is probably all I'm good for. Probably won't be able to do any code contributions.

There are sections of the [viewer in cadquery-gui](https://github.com/jmwright/cadquery-gui/blob/master/assets/js/viewer.js) that you might want to take a look at to see if they can be reused.

**Comment by zignig** [comment]
thanks @jmwright  will investigate and pilfer code as needed. :)

My intent is to have a development helper and a catalogue explorer to start and going into the future a cache proxy for  cqparts (and friends).

**Comment by zignig** [comment]
@jmwright  also check out https://github.com/zignig/cqparts-bucket for some of the messing about I have done with cqparts ( and the awesome of CadQuery ) , looking forward to the pythonOCC transmogrification. Willing to assist on that, we should get @tpaviot on board for the transition.

**Comment by jmwright** [comment]
> It actually watches a directory for any changes to .py files, so ./server -d working_directory , also if you run a script with display(object) in it the server will display it.

Hmm, still not working for me. I have my environment(s) set up in weird ways because of the FreeCAD module development, so that's probably the issue. However, due to #2 I can't seem to figure out what the errors are.

> also check out https://github.com/zignig/cqparts-bucket for some of the messing about I have done with cqparts ( and the awesome of CadQuery )

Cool. I noticed your pizero script. I'm assuming that's a Raspberry Pi Zero?

**Comment by zignig** [comment]
It is  a Rasberry Pi Zero and a basic arduino , I'm making a case that will alter itself based on the board.

**Comment by jmwright** [comment]
I've copied the web-template directory into the virtual environment, and I've filed an issue on cqparts proper about the missing directory. 

I still have to modify the python2.7 line in build.go, and I still don't have anything displayed when I save the file. I see the grid in the browser, and there are no errors in the terminal. However, I do see the following in the console on Firefox in Ubuntu 17.10.
```bash
THREE.WebGLShader: gl.getShaderInfoLog() vertex 0:2(12): warning: extension `GL_ARB_gpu_shader5' unsupported in vertex shader
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME LineBasicMaterial
4: #define VERTEX_TEXTURES
5: #define GAMMA_FACTOR 2
6: #define MAX_BONES 0
7: #define USE_COLOR
8: #define BONE_TEXTURE
9: uniform mat4 modelMatrix;
10: uniform mat4 modelViewMatrix;
11: uniform mat4 projectionMatrix;
12: uniform mat4 viewMatrix;
13: uniform mat3 normalMatrix;
14: uniform vec3 cameraPosition;
15: attribute vec3 position;
16: attribute vec3 normal;
17: attribute vec2 uv;
18: #ifdef USE_COLOR
19: 	attribute vec3 color;
20: #endif
21: #ifdef USE_MORPHTARGETS
22: 	attribute vec3 morphTarget0;
23: 	attribute vec3 morphTarget1;
24: 	attribute vec3 morphTarget2;
25: 	attribute vec3 morphTarget3;
26: 	#ifdef USE_MORPHNORMALS
27: 		attribute vec3 morphNormal0;
28: 		attribute vec3 morphNormal1;
29: 		attribute vec3 morphNormal2;
30: 		attribute vec3 morphNormal3;
31: 	#else
32: 		attribute vec3 morphTarget4;
33: 		attribute vec3 morphTarget5;
34: 		attribute vec3 morphTarget6;
35: 		attr… three.min.js:49:299

```
And this in the console on Chrome in 17.10:
```bash
three.min.js:168 THREE.WebGLRenderer 92
:8080/model/Case/out.gltf:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by jmwright** [comment]
The rendering does work with the new release of cqparts. Im not sure what to do about having to change the python line in build.go.

**Comment by zignig** [comment]
Can you post the change you had to make and I will investigate.

**Comment by zignig** [comment]
very weird. But it's working otherwise ?

**Comment by jmwright** [comment]
Yeah, it's rendering now. I think this issue can be closed since the original problem has been solved.

**Comment by jmwright** [comment]
Thanks for the help.
