### ISSUE TITLE
Where to See Script Errors?

### ISSUE THREAD

**Issue by jmwright** [zignig/cqparts-server#2]
I can't figure out where to see the errors from my script. Where should I look for them?

**Comment by zignig** [comment]
They appear in the server logs at the moment, the intent is to display them formatted in the we pages going forward.

**Comment by jmwright** [comment]
Where are the server logs? I don't see any on disk in the `src/server` directory, and I still don't have any errors showing up in the terminal when I should.

**Comment by zignig** [comment]
they should come up in the STDOUT of the bin server. it runs python in a cmd in /src/server/build.go  the cmd is running python2.7 on my system so that may be the issue.

**Comment by jmwright** [comment]
I don't know if it will help, but here's my terminal output.
```bash
$ ./server -d ~/Downloads/cqparts_demo/ 
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

index.tmpl
[GIN-debug] GET    /                         --> main.main.func1 (3 handlers)
[GIN-debug] GET    /static/*name             --> main.Static (3 handlers)
[GIN-debug] GET    /model/*filepath          --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] HEAD   /model/*filepath          --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] GET    /events                   --> main.event (3 handlers)
[GIN-debug] POST   /notify                   --> main.notify (3 handlers)
[GIN-debug] POST   /snapshot                 --> main.snapshot (3 handlers)
watching : /home/jwright/Downloads/cqparts_demo/
[GIN-debug] Listening and serving HTTP on :8080
test.py

[GIN] 2018/05/26 - 22:02:36 | 200 |     563.958µs |       127.0.0.1 | GET      /
[GIN] 2018/05/26 - 22:02:36 | 404 |         668ns |       127.0.0.1 | GET      /favicon.ico
[GIN] 2018/05/26 - 22:03:37 | 404 |         830ns |       127.0.0.1 | GET      /favicon.ico
event "/home/jwright/Downloads/cqparts_demo/test.py": WRITE
next
event "/home/jwright/Downloads/cqparts_demo/test.py": WRITE
next
event "/home/jwright/Downloads/cqparts_demo/test.py": WRITE
next
event "/home/jwright/Downloads/cqparts_demo/test.py": WRITE
next
event "/home/jwright/Downloads/cqparts_demo/test.py": WRITE
next
event "/home/jwright/Downloads/cqparts_demo/test.py": WRITE
next
```

**Comment by jmwright** [comment]
Nothing seems to make it to STDOUT for me. One of the things I tried was the logging method outlined [here](https://github.com/fragmuffin/cqparts/issues/85#issuecomment-388589229). I was hoping to log out the version of Python the script sees, but can't seem to do it.

**Comment by jmwright** [comment]
On my 17.10 system if Go just calls `python` it will use 2.7.14. I have to explicitly run `python3` to get 3.6.

**Comment by zignig** [comment]
OK I know what's going on. I do my editing in a Vim editor when it is saved it does and atomic move of the file and the server catches the REMOVE , when you are saving  your file it's doing a WRITE and it's not triggering the execution.  What editor are you using ? 

Some minor code changes and it will work, Probably get to it  tonight (UTC+8) as I have RealLife(TM) interrupting my quality coding time.

**Comment by jmwright** [comment]
Thanks!

**Comment by zignig** [comment]
Try a fresh pull and build it should fix your notify issue.

**Comment by jmwright** [comment]
I can see the errors now. Thanks.
